# Your Website Title
title: Luke Lee's Blog

# Your Website URL
url: 'https://lukelee233.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
#ga_index: UA-XXXXXXXX-X
#ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Luke Lee
tagline: Vehicle Routing Problem, NLP, Reinforcement Learning
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: C++ Developer, Milanista
#description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: liwenyanghust@gmail.com
website: lukelee233.github.io # do not add http://
#linkedin: realmelvinchng
github: LukeLee233
#twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - listen